<?php
require_once(__DIR__."/../../app/helpers/session_config.php");

/* ---------------------------------------
   CHECK IF REPORT EXISTS BEFORE PDF
----------------------------------------*/

$reportPath = "D:/XAMPP/htdocs/webcheck360/report.json";

if (!file_exists($reportPath)) {

    // Redirect instead of breaking PDF
    header("Location: /WebCheck360-backup/WebCheck360/public/report.php?error=no_report");
    exit;
}

/* ---------------------------------------
   START PDF GENERATION
----------------------------------------*/

ob_start(); // prevent accidental output

require(__DIR__.'/../../vendor/fpdf/fpdf.php');

$basePath = "D:/XAMPP/htdocs/webcheck360/";

$reportPath = $basePath . "report.json";
$linksPath  = $basePath . "links.json";

// ---------- CHECK FILES ----------
if (!file_exists($reportPath)) {
    die("No scan report found.");
}

$report = json_decode(file_get_contents($reportPath), true);

// links.json is optional (may be empty)
$linksData = [];
if (file_exists($linksPath)) {
    $linksData = json_decode(file_get_contents($linksPath), true);
}

// ---------- SAFE DATA ----------
$website      = $report['website'] ?? 'N/A';
$totalLinks   = $report['totalLinks'] ?? 0;
$brokenLinks  = $report['brokenLinks'] ?? 0;
$suspectLinks = $report['suspectLinks'] ?? 0;

// ---------- HEALTH SCORE ----------
$healthScore = $totalLinks > 0
    ? round((($totalLinks - ($brokenLinks + $suspectLinks)) / $totalLinks) * 100)
    : 100;

// ---------- CREATE PDF ----------
$pdf = new FPDF();
$pdf->AddPage();

// ---------- TITLE ----------
$pdf->SetFont('Arial','B',16);
$pdf->Cell(0,10,'WebCheck360 Website Audit Report',0,1,'C');

$pdf->Ln(5);

// ---------- WEBSITE ----------
$pdf->SetFont('Arial','',12);
$pdf->Cell(0,8,"Website: $website",0,1);

$pdf->Ln(3);

// ---------- SUMMARY ----------
$pdf->SetFont('Arial','B',14);
$pdf->Cell(0,10,'Scan Summary',0,1);

$pdf->SetFont('Arial','',12);
$pdf->Cell(0,8,"Total Links Checked: $totalLinks",0,1);
$pdf->Cell(0,8,"Broken Links Found: $brokenLinks",0,1);
$pdf->Cell(0,8,"Suspect Links Found: $suspectLinks",0,1);
$pdf->Cell(0,8,"Health Score: $healthScore%",0,1);

$pdf->Ln(8);

// ---------- BROKEN LINKS TABLE ----------
$pdf->SetFont('Arial','B',14);
$pdf->Cell(0,10,'Issues Detected',0,1);

$pdf->SetFont('Arial','B',11);
$pdf->Cell(130,8,'URL',1);
$pdf->Cell(30,8,'Status',1);
$pdf->Cell(30,8,'Type',1);
$pdf->Ln();

$pdf->SetFont('Arial','',10);

$issuesFound = false;

if (!empty($linksData)) {
    foreach ($linksData as $link) {

        $url = $link['url'];
        $status = (int)$link['status'];

        if ($status >= 404) {
            $type = "Broken";
        } elseif ($status == 401 || $status == 403) {
            $type = "Suspect";
        } else {
            continue; // skip valid links in audit
        }

        $issuesFound = true;

        $pdf->Cell(130,8,substr($url,0,85),1);
        $pdf->Cell(30,8,$status,1);
        $pdf->Cell(30,8,$type,1);
        $pdf->Ln();
    }
}

if (!$issuesFound) {
    $pdf->Cell(190,8,'No issues detected. Website looks healthy.',1,1,'C');
}

$pdf->Ln(10);

// ---------- FOOTER ----------
$pdf->SetY(-20);
$pdf->SetFont('Arial','I',9);
$pdf->Cell(0,10,'Generated by WebCheck360 Automation Engine',0,0,'C');

ob_end_clean();
$pdf->Output('D', 'WebCheck360_Audit_Report.pdf');
exit;
?>
